♨

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -42,13 +42,13 @@ jobs:
             target: x86_64-unknown-linux-musl
             docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
             build: set -e && yarn build && strip *.node
-          - host: ubuntu-latest
-            target: aarch64-unknown-linux-gnu
-            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
-            build: |-
-              set -e &&
-              yarn build --target aarch64-unknown-linux-gnu &&
-              aarch64-unknown-linux-gnu-strip *.node
+        #  - host: ubuntu-latest
+        #    target: aarch64-unknown-linux-gnu
+        #    docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
+        #    build: |-
+        #      set -e &&
+        #      yarn build --target aarch64-unknown-linux-gnu &&
+        #      aarch64-unknown-linux-gnu-strip *.node
         # - host: ubuntu-latest
         #   target: aarch64-unknown-linux-musl
         #   docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-alpine
@@ -236,46 +236,46 @@ jobs:
         shell: bash
       - name: Test bindings
         run: docker run --rm -v $(pwd):/build -w /build node:${{ matrix.node }}-alpine yarn test
-  test-linux-aarch64-gnu-binding:
-    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
-    needs:
-      - build
-    strategy:
-      fail-fast: false
-      matrix:
-        node:
-          - '18'
-    runs-on: ubuntu-latest
-    steps:
-      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
-      - uses: actions/checkout@v3
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: bindings-aarch64-unknown-linux-gnu
-          path: .
-      - name: List packages
-        run: ls -R .
-        shell: bash
-      - name: Cache NPM dependencies
-        uses: actions/cache@v3
-        with:
-          path: .yarn/cache
-          key: npm-cache-test-linux-aarch64-gnu-${{ matrix.node }}
-      - name: Install dependencies
-        run: |
-          yarn config set supportedArchitectures.cpu "arm64"
-          yarn config set supportedArchitectures.libc "glibc"
-          yarn install
-      - name: Setup and run tests
-        uses: addnab/docker-run-action@v3
-        with:
-          image: ghcr.io/napi-rs/napi-rs/nodejs:aarch64-${{ matrix.node }}
-          options: '-v ${{ github.workspace }}:/build -w /build'
-          run: |
-            set -e
-            yarn test
-            ls -la
+#  test-linux-aarch64-gnu-binding:
+#    name: Test bindings on aarch64-unknown-linux-gnu - node@${{ matrix.node }}
+#    needs:
+#      - build
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        node:
+#          - '18'
+#    runs-on: ubuntu-latest
+#    steps:
+#      - run: docker run --rm --privileged multiarch/qemu-user-static:register --reset
+#      - uses: actions/checkout@v3
+#      - name: Download artifacts
+#        uses: actions/download-artifact@v3
+#        with:
+#          name: bindings-aarch64-unknown-linux-gnu
+#          path: .
+#      - name: List packages
+#        run: ls -R .
+#        shell: bash
+#      - name: Cache NPM dependencies
+#        uses: actions/cache@v3
+#        with:
+#          path: .yarn/cache
+#          key: npm-cache-test-linux-aarch64-gnu-${{ matrix.node }}
+#      - name: Install dependencies
+#        run: |
+#          yarn config set supportedArchitectures.cpu "arm64"
+#          yarn config set supportedArchitectures.libc "glibc"
+#          yarn install
+#      - name: Setup and run tests
+#        uses: addnab/docker-run-action@v3
+#        with:
+#          image: ghcr.io/napi-rs/napi-rs/nodejs:aarch64-${{ matrix.node }}
+#          options: '-v ${{ github.workspace }}:/build -w /build'
+#          run: |
+#            set -e
+#            yarn test
+#            ls -la
 #  test-linux-aarch64-musl-binding:
 #    name: Test bindings on aarch64-unknown-linux-musl - node@${{ matrix.node }}
 #    needs:
@@ -318,7 +318,7 @@ jobs:
       - test-macOS-windows-binding
       - test-linux-x64-gnu-binding
       - test-linux-x64-musl-binding
-      - test-linux-aarch64-gnu-binding
+    # - test-linux-aarch64-gnu-binding
     # - test-linux-aarch64-musl-binding
     steps:
       - uses: actions/checkout@v3
